kind = "web"
previewPath = "/"
title = "NuTube"
version = "1.0.0"
id = "artifacts/nutube"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25429

[services.development]
run = "pnpm --filter @workspace/nutube run dev"

[services.env]
PORT = "25429"
